<?php

namespace UserStories\USBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelefonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefonRepository extends EntityRepository
{
}
